set -u
cd /home/user/market-research-1
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 1, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 2, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 3, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 4, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 5, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 6, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 7, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 8, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 9, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 10, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 11, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "months", "rr_n": 8, "rr_seed": 12, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 1, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 2, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 3, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 4, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 5, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 6, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 7, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
python scripts/strategy_lab.py --candidate strat_l29d_randrearm --params-json '{"b_hi": 0.65, "b_lo": 0.45, "b_mid": 0.55, "floor_lb": 19, "lookback": 16, "max_dist": 0.055, "regime_ma": 18, "lq_min": 5e6, "lq_days": 40, "lq_shift": 0.05, "lq_shift_hi": 0.05, "lq_shift_lo": 0.075, "lq_mode": "strict", "top": 25, "weighting": "invvol", "rr_mode": "runs", "rr_eps": 3, "rr_seed": 8, "rr_to": 1.0}' --universe nse_all --top 25 --results .cache/strategy_lab/l29_dD_results.tsv --best-json .cache/strategy_lab/l29_dD_best.json
wc -l .cache/strategy_lab/l29_dD_results.tsv
